# Generated by Django 5.1.6 on 2025-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="teacherDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TeacherName",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("TeacherAge", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "TeacherPlace",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "TeacherSubject",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "TeacherEmail",
                    models.EmailField(blank=True, max_length=200, null=True),
                ),
                (
                    "TeacherPhone",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
